### ISSUE TITLE
Remove unigine

### ISSUE THREAD

**Issue by jklgrasso** [jacobktm/stress-scripts#1]
[Please. Josh's request as well.](https://benchmark.unigine.com/policies/heaven-advanced-eula)

**Comment by JDKarner** [comment]
https://benchmark.unigine.com/valley#editions

It is also broken on linux, we don't wanna keep using -s ;)

**Comment by jacobktm** [comment]
done with this commit: https://github.com/jacobktm/stress-scripts/commit/d9effb2f4e3acaf7c50da387abf1c1d082b44e32
